In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/data_mordred.csv')
data = data.add_prefix('mordred_')
data.to_csv('data_mordred2.csv', index=False)
data.head()

,mordred_PC_ID,mordred_PC_SMILES,mordred_PC_SpAbs_A,mordred_PC_SpMax_A,mordred_PC_SpDiam_A,mordred_PC_SpAD_A,mordred_PC_SpMAD_A,mordred_PC_LogEE_A,mordred_PC_VE1_A,mordred_PC_VE2_A,...,mordred_Alc_TSRW10,mordred_Alc_MW,mordred_Alc_AMW,mordred_Alc_WPath,mordred_Alc_WPol,mordred_Alc_Zagreb1,mordred_Alc_Zagreb2,mordred_Alc_mZagreb1,mordred_Alc_mZagreb2,mordred_Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,...,51.698677,256.109944,7.317427,796.0,26.0,92.0,104.0,6.305556,4.388889,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,...,46.327745,198.104465,6.831188,394.0,18.0,72.0,80.0,4.083333,3.444444,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,...,54.461996,274.135765,7.029122,1054.0,29.0,106.0,121.0,5.305556,4.722222,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,...,47.806046,212.120115,6.628754,477.0,20.0,78.0,87.0,4.944444,3.611111,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,...,49.060956,228.115030,6.912577,576.0,22.0,82.0,92.0,5.194444,3.944444,78

In [3]:
data = pd.read_csv('data/data_RDKit.csv')
data = data.add_prefix('RDKit_')
data.to_csv('data_RDKit2.csv', index=False)
data.head()

,RDKit_PC_ID,RDKit_PC_SMILES,RDKit_PC_MaxEStateIndex,RDKit_PC_MinEStateIndex,RDKit_PC_MaxAbsEStateIndex,RDKit_PC_MinAbsEStateIndex,RDKit_PC_qed,RDKit_PC_MolWt,RDKit_PC_HeavyAtomMolWt,RDKit_PC_ExactMolWt,...,RDKit_Alc_fr_C_O,RDKit_Alc_fr_C_O_noCOO,RDKit_Alc_fr_aryl_methyl,RDKit_Alc_fr_benzene,RDKit_Alc_fr_bicyclic,RDKit_Alc_fr_ester,RDKit_Alc_fr_ether,RDKit_Alc_fr_methoxy,RDKit_Alc_fr_thiophene,RDKit_Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,1,1,0,2,0,1,1,1,0,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,0,2,0,0,0,0,0,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,0,3,0,0,0,0,0,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,1,2,0,0,0,0,0,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,0,2,0,0,1,1,0,78