In [1]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.decomposition import PCA

In [2]:
def remove_all_zero_col(data):
    data = data.copy()
    for col in data.columns:
        if (data[col] == 0).all():
            data.drop(col, axis=1, inplace=True)
    return data

In [3]:
data = pd.read_csv("../source/smiles.csv")
Yield = pd.DataFrame(data['Yield'], columns=['Yield'])
PC_ID = pd.DataFrame(data['PC_ID'], columns=['PC_ID'])
Alc_ID = pd.DataFrame(data['Alc_ID'], columns=['Alc_ID'])
smiles_PC = pd.DataFrame(data['PC_SMILES'], columns=['PC_SMILES'])
smiles_Alc = pd.DataFrame(data['Alc_SMILES'], columns=['Alc_SMILES'])

print(Yield)
print(PC_ID)
print(Alc_ID)

     Yield
0       14
1        4
2       18
3       11
4       78
..     ...
191      5
192      0
193      0
194     36
195     61

[196 rows x 1 columns]
    PC_ID
0     PC1
1     PC1
2     PC1
3     PC1
4     PC1
..    ...
191  PC14
192  PC14
193  PC14
194  PC14
195  PC14

[196 rows x 1 columns]
    Alc_ID
0     Alc1
1     Alc2
2     Alc3
3     Alc4
4     Alc5
..     ...
191  Alc10
192  Alc11
193  Alc12
194  Alc13
195  Alc14

[196 rows x 1 columns]

In [4]:
#PC
mf_p = []
for i in range(0,196):
    mol_p = Chem.MolFromSmiles(data["PC_SMILES"][i])
    fp_p = AllChem.GetMorganFingerprintAsBitVect(mol_p, 2, 2048)
    mf_p.append(np.array(fp_p, int))

df_p = pd.DataFrame(mf_p)
df_p = df_p.add_prefix('PC_MF_')
print(df_p.shape)
df_2_p = remove_all_zero_col(df_p)
print(df_2_p.shape)
df_2_p.head()

(196, 2048)
(196, 102)

,PC_MF_1,PC_MF_9,PC_MF_105,PC_MF_114,PC_MF_119,PC_MF_162,PC_MF_184,PC_MF_203,PC_MF_216,PC_MF_282,...,PC_MF_1848,PC_MF_1855,PC_MF_1859,PC_MF_1873,PC_MF_1902,PC_MF_1917,PC_MF_1925,PC_MF_1928,PC_MF_1950,PC_MF_1985
0,0,0,0,0,0,0,0,0,0,1,...,1,0,1,1,1,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,1,0,1,1,1,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,1,...,1,0,1,1,1,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,1,0,1,1,1,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,1,...,1,0,1,1,1,0,1,0,0,0

In [5]:
#Alc
mf_a = []
for i in range(0,196):
    mol_a = Chem.MolFromSmiles(data["Alc_SMILES"][i])
    fp_a = AllChem.GetMorganFingerprintAsBitVect(mol_a, 2, 2048)
    mf_a.append(np.array(fp_a, int))

df_a = pd.DataFrame(mf_a)
df_a = df_a.add_prefix('Alc_MF_')
print(df_a.shape)
df_2_a = remove_all_zero_col(df_a)
print(df_2_a.shape)
df_2_a.head()

(196, 2048)
(196, 108)

,Alc_MF_1,Alc_MF_14,Alc_MF_63,Alc_MF_77,Alc_MF_79,Alc_MF_80,Alc_MF_94,Alc_MF_114,Alc_MF_140,Alc_MF_145,...,Alc_MF_1863,Alc_MF_1873,Alc_MF_1905,Alc_MF_1906,Alc_MF_1908,Alc_MF_1917,Alc_MF_1920,Alc_MF_1964,Alc_MF_1970,Alc_MF_2029
0,1,0,0,0,1,1,0,0,0,1,...,0,1,0,0,0,1,0,0,0,0
1,1,0,0,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,0,0,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
3,1,0,0,0,1,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
4,1,0,0,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [6]:
MF = pd.concat([PC_ID, smiles_PC, df_2_p, Alc_ID, smiles_Alc, df_2_a, Yield], axis=1, join='inner')
MF.to_csv('../data/data_MF.csv', index = False)
MF

,PC_ID,PC_SMILES,PC_MF_1,PC_MF_9,PC_MF_105,PC_MF_114,PC_MF_119,PC_MF_162,PC_MF_184,PC_MF_203,...,Alc_MF_1873,Alc_MF_1905,Alc_MF_1906,Alc_MF_1908,Alc_MF_1917,Alc_MF_1920,Alc_MF_1964,Alc_MF_1970,Alc_MF_2029,Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,5
192,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,0,0,0,0,0,0,1,0,...,1,0,1,0,0,0,0,0,0,0
193,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
194,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,0,0,0,0,0,0,1,0,...,1,1,0,0,0,0,0,0,1,36
195,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,0,0,0,0,0,0,1,0,...,1,1,0,0,0,0,0,0,1,61

In [7]:
#PC, PCA
X_pc = np.array(df_2_p)
pca = PCA(n_components=7)
X_pca_pc = pca.fit(X_pc).transform(X_pc)
print("Before: {}".format(str(X_pc.shape)))
print("After: {}".format(str(X_pca_pc.shape)))
print('sum of explained variance ratio: {0}'.format(sum(pca.explained_variance_ratio_)))
df_3_p = pd.DataFrame(X_pca_pc)
df_3_p = df_3_p.add_prefix('MF_PC_')
df_3_p.head()

Before: (196, 102)
After: (196, 7)
sum of explained variance ratio: 0.8384635039825341

,MF_PC_0,MF_PC_1,MF_PC_2,MF_PC_3,MF_PC_4,MF_PC_5,MF_PC_6
0,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14
1,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14
2,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14
3,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14
4,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14

In [8]:
#Alc, PCA
X_alc = np.array(df_2_a)
pca = PCA(n_components=7)
X_pca_alc = pca.fit(X_alc).transform(X_alc)
print("Before: {}".format(str(X_alc.shape)))
print("After: {}".format(str(X_pca_alc.shape)))
print('sum of explained variance ratio: {0}'.format(sum(pca.explained_variance_ratio_)))
df_3_a = pd.DataFrame(X_pca_alc)
df_3_a = df_3_a.add_prefix('MF_Alc_')
df_3_a.head()

Before: (196, 108)
After: (196, 7)
sum of explained variance ratio: 0.8422292493037971

   MF_Alc_0  MF_Alc_1  MF_Alc_2  MF_Alc_3  MF_Alc_4  MF_Alc_5  MF_Alc_6
0 -0.470673 -1.147685 -1.930061 -0.341193 -0.210513 -1.377728  1.663971
1 -0.816945 -0.637053 -0.001759 -0.448967  0.197548  0.348464  0.025442
2 -1.058596 -0.596705 -0.370602 -0.672889  0.212105  0.740141  0.070643
3 -0.851804 -0.667542 -0.732906 -0.555728  0.245927  0.563972 -0.022813
4  0.212236 -0.583472 -1.367581 -0.776568  0.003098 -0.104066 -1.324936

In [9]:
MF_pca = pd.concat([PC_ID, smiles_PC, df_3_p, Alc_ID, smiles_Alc, df_3_a, Yield], axis=1, join='inner')
MF_pca.to_csv('../data/data_MF_pca.csv', index = False)
MF_pca

,PC_ID,PC_SMILES,MF_PC_0,MF_PC_1,MF_PC_2,MF_PC_3,MF_PC_4,MF_PC_5,MF_PC_6,Alc_ID,Alc_SMILES,MF_Alc_0,MF_Alc_1,MF_Alc_2,MF_Alc_3,MF_Alc_4,MF_Alc_5,MF_Alc_6,Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14,Alc1,OC(CC1=CC=CC=C1)C2=CC=C(C(OC)=O)C=C2,-0.470673,-1.147685,-1.930061,-0.341193,-0.210513,-1.377728,1.663971,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14,Alc2,OC(CC1=CC=CC=C1)C2=CC=CC=C2,-0.816945,-0.637053,-0.001759,-0.448967,0.197548,0.348464,0.025442,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14,Alc3,OC(CC1=CC=CC=C1)C2=CC=C(C3=CC=CC=C3)C=C2,-1.058596,-0.596705,-0.370602,-0.672889,0.212105,0.740141,0.070643,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14,Alc4,OC(CC1=CC=CC=C1)C2=CC=C(C)C=C2,-0.851804,-0.667542,-0.732906,-0.555728,0.245927,0.563972,-0.022813,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,-1.835731,-1.660882,0.352013,0.139121,-1.167229,-7.236743e-16,1.578092e-14,Alc5,OC(CC1=CC=CC=C1)C2=CC=C(OC)C=C2,0.212236,-0.583472,-1.367581,-0.776568,0.003098,-0.104066,-1.324936,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,-2.043791,-1.802628,-0.332624,-0.678382,-1.563520,1.612360e-15,-3.918558e-15,Alc10,OC(CC1=CC=CC=C1)C2=CC=CS2,-0.484757,-1.171367,2.016056,-0.104426,2.304708,0.057529,0.396767,5
192,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,-2.043791,-1.802628,-0.332624,-0.678382,-1.563520,1.612360e-15,-3.918558e-15,Alc11,OC(CC1=CC=CC=C1)C2=CC=C3C(C=CC=C3)=C2,-1.093087,0.172941,0.225805,-0.207301,-0.979092,1.598100,-0.290465,0
193,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,-2.043791,-1.802628,-0.332624,-0.678382,-1.563520,1.612360e-15,-3.918558e-15,Alc12,OC(CC1=CC=CC=C1)C2=C3C(C=CC=C3)=CC=C2,-0.561737,-1.457762,2.098512,0.407956,-2.077327,-0.419377,0.344578,0
194,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,-2.043791,-1.802628,-0.332624,-0.678382,-1.563520,1.612360e-15,-3.918558e-15,Alc13,OC(CC1=CC=CC=C1)C2=CC(OCO3)=C3C=C2,-1.852382,2.458300,0.349073,-0.039493,0.054161,-0.694896,-0.056261,36
195,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,-2.043791,-1.802628,-0.332624,-0.678382,-1.563520,1.612360e-15,-3.918558e-15,Alc14,OC(CC1=CC=CC=C1)C2=CC=C3C(OCCO3)=C2,-1.852382,2.458300,0.349073,-0.039493,0.054161,-0.694896,-0.056261,61