In [1]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from mordred import Calculator, descriptors
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
def remove_all_zero_col(data):
    data = data.copy()
    for col in data.columns:
        if (data[col] == 0).all():
            data.drop(col, axis=1, inplace=True)
    return data

In [3]:
data = pd.read_csv("../source/smiles.csv")
Yield = pd.DataFrame(data['Yield'], columns=['Yield'])
PC_ID = pd.DataFrame(data['PC_ID'], columns=['PC_ID'])
Alc_ID = pd.DataFrame(data['Alc_ID'], columns=['Alc_ID'])
smiles_PC = pd.DataFrame(data['PC_SMILES'], columns=['PC_SMILES'])
smiles_Alc = pd.DataFrame(data['Alc_SMILES'], columns=['Alc_SMILES'])

print(Yield)
print(PC_ID)
print(Alc_ID)

     Yield
0       14
1        4
2       18
3       11
4       78
..     ...
191      5
192      0
193      0
194     36
195     61

[196 rows x 1 columns]
    PC_ID
0     PC1
1     PC1
2     PC1
3     PC1
4     PC1
..    ...
191  PC14
192  PC14
193  PC14
194  PC14
195  PC14

[196 rows x 1 columns]
    Alc_ID
0     Alc1
1     Alc2
2     Alc3
3     Alc4
4     Alc5
..     ...
191  Alc10
192  Alc11
193  Alc12
194  Alc13
195  Alc14

[196 rows x 1 columns]

In [4]:
#PC
data['Mol'] = data["PC_SMILES"].apply(Chem.MolFromSmiles)

calc_mordred_p = Calculator(descriptors, ignore_3D=True)
desc_mordred_p = calc_mordred_p.pandas(data['Mol'])

mordred_p = desc_mordred_p.astype(str)
masks_p = mordred_p.apply(lambda d: d.str.contains('[a-zA-Z]' ,na=False))
mordred_p = mordred_p[~masks_p]
mordred_p = mordred_p.astype(float)
df_mordred_p = mordred_p.dropna(how="any", axis="columns")

print(df_mordred_p.shape)
df_mordred_p_2 = remove_all_zero_col(df_mordred_p)
df_mordred_p_2 = df_mordred_p_2.add_prefix('PC_')
print(df_mordred_p_2.shape)
df_mordred_p_2.head()

100%|████████████████████████████████████████████████████████████████████████████████| 196/196 [00:05<00:00, 37.89it/s]

(196, 1413)
(196, 1153)

,PC_SpAbs_A,PC_SpMax_A,PC_SpDiam_A,PC_SpAD_A,PC_SpMAD_A,PC_LogEE_A,PC_VE1_A,PC_VE2_A,PC_VE3_A,PC_VR1_A,...,PC_SRW10,PC_TSRW10,PC_MW,PC_AMW,PC_WPath,PC_WPol,PC_Zagreb1,PC_Zagreb2,PC_mZagreb1,PC_mZagreb2
0,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,1.850604,90.742708,...,10.188629,50.954226,238.081392,7.680045,432.0,33.0,96.0,119.0,5.618056,3.611111
1,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,1.850604,90.742708,...,10.188629,50.954226,238.081392,7.680045,432.0,33.0,96.0,119.0,5.618056,3.611111
2,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,1.850604,90.742708,...,10.188629,50.954226,238.081392,7.680045,432.0,33.0,96.0,119.0,5.618056,3.611111
3,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,1.850604,90.742708,...,10.188629,50.954226,238.081392,7.680045,432.0,33.0,96.0,119.0,5.618056,3.611111
4,22.379482,2.554748,5.109496,22.379482,1.31644,3.798188,3.743331,0.220196,1.850604,90.742708,...,10.188629,50.954226,238.081392,7.680045,432.0,33.0,96.0,119.0,5.618056,3.611111

In [5]:
#Alc
data['Mol'] = data["Alc_SMILES"].apply(Chem.MolFromSmiles)

calc_mordred_a = Calculator(descriptors, ignore_3D=True)
desc_mordred_a = calc_mordred_a.pandas(data['Mol'])

mordred_a = desc_mordred_a.astype(str)
masks_a = mordred_a.apply(lambda d: d.str.contains('[a-zA-Z]' ,na=False))
mordred_a = mordred_a[~masks_a]
mordred_a = mordred_a.astype(float)
df_mordred_a = mordred_a.dropna(how="any", axis="columns")

print(df_mordred_a.shape)
df_mordred_a_2 = remove_all_zero_col(df_mordred_a)
df_mordred_a_2 = df_mordred_a_2.add_prefix('Alc_')
print(df_mordred_a_2.shape)
df_mordred_a_2.head()

100%|████████████████████████████████████████████████████████████████████████████████| 196/196 [00:04<00:00, 45.34it/s]

(196, 1422)
(196, 1145)

,Alc_SpAbs_A,Alc_SpMax_A,Alc_SpDiam_A,Alc_SpAD_A,Alc_SpMAD_A,Alc_LogEE_A,Alc_VE1_A,Alc_VE2_A,Alc_VE3_A,Alc_VR1_A,...,Alc_SRW10,Alc_TSRW10,Alc_MW,Alc_AMW,Alc_WPath,Alc_WPol,Alc_Zagreb1,Alc_Zagreb2,Alc_mZagreb1,Alc_mZagreb2
0,24.620447,2.317388,4.634775,24.620447,1.295813,3.849074,3.919870,0.206309,2.007912,112.728669,...,9.573663,51.698677,256.109944,7.317427,796.0,26.0,92.0,104.0,6.305556,4.388889
1,19.757720,2.268623,4.537246,19.757720,1.317181,3.621267,3.642614,0.242841,1.698167,69.600440,...,9.246962,46.327745,198.104465,6.831188,394.0,18.0,72.0,80.0,4.083333,3.444444
2,28.146119,2.339750,4.679499,28.146119,1.340291,3.970698,4.110677,0.195747,2.155525,147.042766,...,9.747243,54.461996,274.135765,7.029122,1054.0,29.0,106.0,121.0,5.305556,4.722222
3,20.509223,2.288246,4.576491,20.509223,1.281826,3.685820,3.724763,0.232798,1.785007,78.328298,...,9.370331,47.806046,212.120115,6.628754,477.0,20.0,78.0,87.0,4.944444,3.611111
4,22.188276,2.295849,4.591698,22.188276,1.305193,3.741643,3.786970,0.222763,1.862195,89.769451,...,9.423595,49.060956,228.115030,6.912577,576.0,22.0,82.0,92.0,5.194444,3.944444

In [6]:
mordred = pd.concat([PC_ID, smiles_PC, df_mordred_p_2, Alc_ID, smiles_Alc, df_mordred_a_2, Yield], axis=1, join='inner')
mordred.to_csv('../data/data_mordred.csv', index = False)
mordred

,PC_ID,PC_SMILES,PC_SpAbs_A,PC_SpMax_A,PC_SpDiam_A,PC_SpAD_A,PC_SpMAD_A,PC_LogEE_A,PC_VE1_A,PC_VE2_A,...,Alc_TSRW10,Alc_MW,Alc_AMW,Alc_WPath,Alc_WPol,Alc_Zagreb1,Alc_Zagreb2,Alc_mZagreb1,Alc_mZagreb2,Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.316440,3.798188,3.743331,0.220196,...,51.698677,256.109944,7.317427,796.0,26.0,92.0,104.0,6.305556,4.388889,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.316440,3.798188,3.743331,0.220196,...,46.327745,198.104465,6.831188,394.0,18.0,72.0,80.0,4.083333,3.444444,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.316440,3.798188,3.743331,0.220196,...,54.461996,274.135765,7.029122,1054.0,29.0,106.0,121.0,5.305556,4.722222,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.316440,3.798188,3.743331,0.220196,...,47.806046,212.120115,6.628754,477.0,20.0,78.0,87.0,4.944444,3.611111,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,22.379482,2.554748,5.109496,22.379482,1.316440,3.798188,3.743331,0.220196,...,49.060956,228.115030,6.912577,576.0,22.0,82.0,92.0,5.194444,3.944444,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,37.162733,2.643357,5.286715,37.162733,1.376398,4.262014,4.371426,0.161905,...,58.086633,204.060886,7.848496,323.0,15.0,68.0,76.0,3.833333,3.194444,5
192,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,37.162733,2.643357,5.286715,37.162733,1.376398,4.262014,4.371426,0.161905,...,52.216823,248.120115,7.089146,748.0,27.0,98.0,113.0,4.805556,4.222222,0
193,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,37.162733,2.643357,5.286715,37.162733,1.376398,4.262014,4.371426,0.161905,...,52.300104,248.120115,7.089146,712.0,28.0,98.0,114.0,4.805556,4.250000,0
194,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,37.162733,2.643357,5.286715,37.162733,1.376398,4.262014,4.371426,0.161905,...,64.521606,242.094294,7.565447,641.0,24.0,94.0,109.0,4.555556,3.972222,36
195,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,37.162733,2.643357,5.286715,37.162733,1.376398,4.262014,4.371426,0.161905,...,52.216823,256.109944,7.317427,748.0,27.0,98.0,113.0,4.805556,4.222222,61

In [7]:
#PC, PCA
X_pc = np.array(df_mordred_p_2)
sc = StandardScaler()
X_sc_pc = sc.fit(X_pc).transform(X_pc)
pca = PCA(n_components=5)
X_pca_pc = pca.fit(X_sc_pc).transform(X_sc_pc)
print("Before: {}".format(str(X_sc_pc.shape)))
print("After: {}".format(str(X_pca_pc.shape)))
print('sum of explained variance ratio: {0}'.format(sum(pca.explained_variance_ratio_)))
df_mordred_p_3 = pd.DataFrame(X_pca_pc)
df_mordred_p_3 = df_mordred_p_3.add_prefix('mordred_PC_')
df_mordred_p_3.head()

Before: (196, 1153)
After: (196, 5)
sum of explained variance ratio: 0.8382605100759384

   mordred_PC_0  mordred_PC_1  mordred_PC_2  mordred_PC_3  mordred_PC_4
0      7.200802    -17.668638      0.426786     28.770577      6.206296
1      7.200802    -17.668638      0.426786     28.770577      6.206296
2      7.200802    -17.668638      0.426786     28.770577      6.206296
3      7.200802    -17.668638      0.426786     28.770577      6.206296
4      7.200802    -17.668638      0.426786     28.770577      6.206296

In [8]:
#Alc, PCA
X_alc = np.array(df_mordred_a_2)
sc = StandardScaler()
X_sc_alc = sc.fit(X_alc).transform(X_alc)
pca = PCA(n_components=5)
X_pca_alc = pca.fit(X_sc_alc).transform(X_sc_alc)
print("Before: {}".format(str(X_sc_alc.shape)))
print("After: {}".format(str(X_pca_alc.shape)))
print('sum of explained variance ratio: {0}'.format(sum(pca.explained_variance_ratio_)))
df_mordred_a_3 = pd.DataFrame(X_pca_alc)
df_mordred_a_3 = df_mordred_a_3.add_prefix('mordred_Alc_')
df_mordred_a_3.head()

Before: (196, 1145)
After: (196, 5)
sum of explained variance ratio: 0.8332805283783011

   mordred_Alc_0  mordred_Alc_1  mordred_Alc_2  mordred_Alc_3  mordred_Alc_4
0     -11.714690      -6.822841      14.114448      -1.521686      29.809936
1      33.099934       2.951164      -7.586083       5.978377       2.553950
2     -14.621947      28.805600      -0.840053      -5.971193       5.315228
3      23.625369       0.661946      -9.500574      -8.115361      -3.419895
4       9.960979      -7.691830      -0.359370      -7.888557       3.458111

In [9]:
mordred_pca = pd.concat([PC_ID, smiles_PC, df_mordred_p_3, Alc_ID, smiles_Alc, df_mordred_a_3, Yield], axis=1, join='inner')
mordred_pca.to_csv('../data/data_mordred_pca.csv', index = False)
mordred_pca

,PC_ID,PC_SMILES,mordred_PC_0,mordred_PC_1,mordred_PC_2,mordred_PC_3,mordred_PC_4,Alc_ID,Alc_SMILES,mordred_Alc_0,mordred_Alc_1,mordred_Alc_2,mordred_Alc_3,mordred_Alc_4,Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,7.200802,-17.668638,0.426786,28.770577,6.206296,Alc1,OC(CC1=CC=CC=C1)C2=CC=C(C(OC)=O)C=C2,-11.714690,-6.822841,14.114448,-1.521686,29.809936,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,7.200802,-17.668638,0.426786,28.770577,6.206296,Alc2,OC(CC1=CC=CC=C1)C2=CC=CC=C2,33.099934,2.951164,-7.586083,5.978377,2.553950,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,7.200802,-17.668638,0.426786,28.770577,6.206296,Alc3,OC(CC1=CC=CC=C1)C2=CC=C(C3=CC=CC=C3)C=C2,-14.621947,28.805600,-0.840053,-5.971193,5.315228,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,7.200802,-17.668638,0.426786,28.770577,6.206296,Alc4,OC(CC1=CC=CC=C1)C2=CC=C(C)C=C2,23.625369,0.661946,-9.500574,-8.115361,-3.419895,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,7.200802,-17.668638,0.426786,28.770577,6.206296,Alc5,OC(CC1=CC=CC=C1)C2=CC=C(OC)C=C2,9.960979,-7.691830,-0.359370,-7.888557,3.458111,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,52.091951,-32.684901,5.501424,-10.358381,1.167446,Alc10,OC(CC1=CC=CC=C1)C2=CC=CS2,47.282187,-9.209036,5.816920,7.729108,-0.753545,5
192,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,52.091951,-32.684901,5.501424,-10.358381,1.167446,Alc11,OC(CC1=CC=CC=C1)C2=CC=C3C(C=CC=C3)=C2,-1.706180,23.002333,0.712413,-2.276278,-4.123323,0
193,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,52.091951,-32.684901,5.501424,-10.358381,1.167446,Alc12,OC(CC1=CC=CC=C1)C2=C3C(C=CC=C3)=CC=C2,-4.385096,24.211153,-3.198486,10.590387,-1.904466,0
194,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,52.091951,-32.684901,5.501424,-10.358381,1.167446,Alc13,OC(CC1=CC=CC=C1)C2=CC(OCO3)=C3C=C2,-1.575475,-5.792163,22.969051,-4.134971,-12.126234,36
195,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,52.091951,-32.684901,5.501424,-10.358381,1.167446,Alc14,OC(CC1=CC=CC=C1)C2=CC=C3C(OCCO3)=C2,-12.400760,-2.862124,15.638962,-2.537081,-12.257474,61