In [1]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import PandasTools
from rdkit.Chem import Descriptors
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import warnings

Failed to find the pandas get_adjustment() function to patch
Failed to patch pandas - PandasTools will have limited functionality

In [2]:
def remove_all_zero_col(data):
    data = data.copy()
    for col in data.columns:
        if (data[col] == 0).all():
            data.drop(col, axis=1, inplace=True)
    return data

In [3]:
warnings.filterwarnings('ignore', category=pd.errors.PerformanceWarning)

In [4]:
data = pd.read_csv("../source/smiles.csv")
Yield = pd.DataFrame(data['Yield'], columns=['Yield'])
PC_ID = pd.DataFrame(data['PC_ID'], columns=['PC_ID'])
Alc_ID = pd.DataFrame(data['Alc_ID'], columns=['Alc_ID'])
df_PC = pd.DataFrame(data['PC_SMILES'], columns=['PC_SMILES'])
df_Alc = pd.DataFrame(data['Alc_SMILES'], columns=['Alc_SMILES'])
smiles_PC = pd.DataFrame(data['PC_SMILES'], columns=['PC_SMILES'])
smiles_Alc = pd.DataFrame(data['Alc_SMILES'], columns=['Alc_SMILES'])

print(Yield)
print(PC_ID)
print(Alc_ID)

     Yield
0       14
1        4
2       18
3       11
4       78
..     ...
191      5
192      0
193      0
194     36
195     61

[196 rows x 1 columns]
    PC_ID
0     PC1
1     PC1
2     PC1
3     PC1
4     PC1
..    ...
191  PC14
192  PC14
193  PC14
194  PC14
195  PC14

[196 rows x 1 columns]
    Alc_ID
0     Alc1
1     Alc2
2     Alc3
3     Alc4
4     Alc5
..     ...
191  Alc10
192  Alc11
193  Alc12
194  Alc13
195  Alc14

[196 rows x 1 columns]

In [5]:
#PC
PandasTools.AddMoleculeColumnToFrame(df_PC,'PC_SMILES')
for i,j in Descriptors.descList:
    df_PC[i] = df_PC.ROMol.map(j)
df_PC = df_PC.add_prefix('PC_')

df_p = df_PC.drop(columns=['PC_PC_SMILES', 'PC_ROMol'])
print(df_p.shape)
df_2_p = remove_all_zero_col(df_p)
df_2_p = df_2_p.dropna(how='any', axis=1)
print(df_2_p.shape)
df_2_p.head()

Failed to patch pandas - unable to change molecule rendering

(196, 208)
(196, 129)

,PC_MaxEStateIndex,PC_MinEStateIndex,PC_MaxAbsEStateIndex,PC_MinAbsEStateIndex,PC_qed,PC_MolWt,PC_HeavyAtomMolWt,PC_ExactMolWt,PC_NumValenceElectrons,PC_MaxPartialCharge,...,PC_fr_aniline,PC_fr_aryl_methyl,PC_fr_benzene,PC_fr_bicyclic,PC_fr_ether,PC_fr_halogen,PC_fr_ketone,PC_fr_methoxy,PC_fr_para_hydroxylation,PC_fr_pyridine
0,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,84,0.192322,...,0,0,2,2,0,0,1,0,0,0
1,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,84,0.192322,...,0,0,2,2,0,0,1,0,0,0
2,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,84,0.192322,...,0,0,2,2,0,0,1,0,0,0
3,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,84,0.192322,...,0,0,2,2,0,0,1,0,0,0
4,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,84,0.192322,...,0,0,2,2,0,0,1,0,0,0

In [6]:
#Alc
PandasTools.AddMoleculeColumnToFrame(df_Alc,'Alc_SMILES')
for i,j in Descriptors.descList:
    df_Alc[i] = df_Alc.ROMol.map(j)
df_Alc = df_Alc.add_prefix('Alc_')

df_a = df_Alc.drop(columns=['Alc_Alc_SMILES', 'Alc_ROMol'])
print(df_a.shape)
df_2_a = remove_all_zero_col(df_a)
df_2_a = df_2_a.dropna(how='any', axis=1)
print(df_2_a.shape)
df_2_a.head()

Failed to patch pandas - unable to change molecule rendering

(196, 208)
(196, 118)

,Alc_MaxEStateIndex,Alc_MinEStateIndex,Alc_MaxAbsEStateIndex,Alc_MinAbsEStateIndex,Alc_qed,Alc_MolWt,Alc_HeavyAtomMolWt,Alc_ExactMolWt,Alc_NumValenceElectrons,Alc_MaxPartialCharge,...,Alc_fr_Al_OH_noTert,Alc_fr_C_O,Alc_fr_C_O_noCOO,Alc_fr_aryl_methyl,Alc_fr_benzene,Alc_fr_bicyclic,Alc_fr_ester,Alc_fr_ether,Alc_fr_methoxy,Alc_fr_thiophene
0,11.300882,-0.574910,11.300882,0.371204,0.855519,256.301,240.173,256.109944,98,0.337342,...,1,1,1,0,2,0,1,1,1,0
1,9.973947,-0.408704,9.973947,0.408704,0.803505,198.265,184.153,198.104465,76,0.082988,...,1,0,0,0,2,0,0,0,0,0
2,10.335408,-0.460904,10.335408,0.460904,0.735116,274.363,256.219,274.135765,104,0.082989,...,1,0,0,0,3,0,0,0,0,0
3,10.064839,-0.413889,10.064839,0.413889,0.827497,212.292,196.164,212.120115,82,0.082988,...,1,0,0,1,2,0,0,0,0,0
4,10.096727,-0.469161,10.096727,0.469161,0.871362,228.291,212.163,228.115030,88,0.118381,...,1,0,0,0,2,0,0,1,1,0

In [7]:
RDKit = pd.concat([PC_ID, smiles_PC, df_2_p, Alc_ID, smiles_Alc, df_2_a, Yield], axis=1, join='inner')
RDKit.to_csv('../data/data_RDKit.csv', index = False)
RDKit

,PC_ID,PC_SMILES,PC_MaxEStateIndex,PC_MinEStateIndex,PC_MaxAbsEStateIndex,PC_MinAbsEStateIndex,PC_qed,PC_MolWt,PC_HeavyAtomMolWt,PC_ExactMolWt,...,Alc_fr_C_O,Alc_fr_C_O_noCOO,Alc_fr_aryl_methyl,Alc_fr_benzene,Alc_fr_bicyclic,Alc_fr_ester,Alc_fr_ether,Alc_fr_methoxy,Alc_fr_thiophene,Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,1,1,0,2,0,1,1,1,0,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,0,2,0,0,0,0,0,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,0,3,0,0,0,0,0,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,1,2,0,0,0,0,0,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,12.417963,-1.694437,12.417963,0.183356,0.642067,238.362,224.25,238.081392,...,0,0,0,2,0,0,1,1,0,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,13.280602,-2.538850,13.280602,0.135359,0.441341,362.504,344.36,362.112692,...,0,0,0,1,0,0,0,0,1,5
192,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,13.280602,-2.538850,13.280602,0.135359,0.441341,362.504,344.36,362.112692,...,0,0,0,3,1,0,0,0,0,0
193,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,13.280602,-2.538850,13.280602,0.135359,0.441341,362.504,344.36,362.112692,...,0,0,0,3,1,0,0,0,0,0
194,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,13.280602,-2.538850,13.280602,0.135359,0.441341,362.504,344.36,362.112692,...,0,0,0,2,1,0,2,0,0,36
195,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,13.280602,-2.538850,13.280602,0.135359,0.441341,362.504,344.36,362.112692,...,0,0,0,2,1,0,2,0,0,61

In [8]:
#PC, PCA
X_pc = np.array(df_2_p)
sc = StandardScaler()
X_sc_pc = sc.fit(X_pc).transform(X_pc)
pca = PCA(n_components=7)
X_pca_pc = pca.fit(X_sc_pc).transform(X_sc_pc)
print("Before: {}".format(str(X_sc_pc.shape)))
print("After: {}".format(str(X_pca_pc.shape)))
print('sum of explained variance ratio: {0}'.format(sum(pca.explained_variance_ratio_)))
df_3_p = pd.DataFrame(X_pca_pc)
df_3_p = df_3_p.add_prefix('RDKit_PC_')
df_3_p.head()

Before: (196, 129)
After: (196, 7)
sum of explained variance ratio: 0.849563793667702

,RDKit_PC_0,RDKit_PC_1,RDKit_PC_2,RDKit_PC_3,RDKit_PC_4,RDKit_PC_5,RDKit_PC_6
0,4.030498,-2.74358,-1.27723,-2.91295,0.715598,-2.968826,1.661883
1,4.030498,-2.74358,-1.27723,-2.91295,0.715598,-2.968826,1.661883
2,4.030498,-2.74358,-1.27723,-2.91295,0.715598,-2.968826,1.661883
3,4.030498,-2.74358,-1.27723,-2.91295,0.715598,-2.968826,1.661883
4,4.030498,-2.74358,-1.27723,-2.91295,0.715598,-2.968826,1.661883

In [9]:
#Alc, PCA
X_alc = np.array(df_2_a)
sc = StandardScaler()
X_sc_alc = sc.fit(X_alc).transform(X_alc)
pca = PCA(n_components=5)
X_pca_alc = pca.fit(X_sc_alc).transform(X_sc_alc)
print("Before: {}".format(str(X_sc_alc.shape)))
print("After: {}".format(str(X_pca_alc.shape)))
print('sum of explained variance ratio: {0}'.format(sum(pca.explained_variance_ratio_)))
df_3_a = pd.DataFrame(X_pca_alc)
df_3_a = df_3_a.add_prefix('RDKit_Alc_')
df_3_a.head()

Before: (196, 118)
After: (196, 5)
sum of explained variance ratio: 0.8700222860396271

   RDKit_Alc_0  RDKit_Alc_1  RDKit_Alc_2  RDKit_Alc_3  RDKit_Alc_4
0    -3.932533    -1.975850    13.050803     0.754757    -1.649219
1     8.561327    -2.374988    -1.085162    -3.141770    -4.047161
2     0.733756    12.623610     0.275732     0.198890     0.706347
3     6.855471    -1.237513    -0.676649    -4.379282    -3.742667
4     1.115037    -2.939343    -1.065685    -1.497640    -2.268652

In [10]:
RDKit_pca = pd.concat([PC_ID, smiles_PC, df_3_p, Alc_ID, smiles_Alc, df_3_a, Yield], axis=1, join='inner')
RDKit_pca.to_csv('../data/data_RDKit_pca.csv', index = False)
RDKit_pca

,PC_ID,PC_SMILES,RDKit_PC_0,RDKit_PC_1,RDKit_PC_2,RDKit_PC_3,RDKit_PC_4,RDKit_PC_5,RDKit_PC_6,Alc_ID,Alc_SMILES,RDKit_Alc_0,RDKit_Alc_1,RDKit_Alc_2,RDKit_Alc_3,RDKit_Alc_4,Yield
0,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,4.030498,-2.743580,-1.277230,-2.912950,0.715598,-2.968826,1.661883,Alc1,OC(CC1=CC=CC=C1)C2=CC=C(C(OC)=O)C=C2,-3.932533,-1.975850,13.050803,0.754757,-1.649219,14
1,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,4.030498,-2.743580,-1.277230,-2.912950,0.715598,-2.968826,1.661883,Alc2,OC(CC1=CC=CC=C1)C2=CC=CC=C2,8.561327,-2.374988,-1.085162,-3.141770,-4.047161,4
2,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,4.030498,-2.743580,-1.277230,-2.912950,0.715598,-2.968826,1.661883,Alc3,OC(CC1=CC=CC=C1)C2=CC=C(C3=CC=CC=C3)C=C2,0.733756,12.623610,0.275732,0.198890,0.706347,18
3,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,4.030498,-2.743580,-1.277230,-2.912950,0.715598,-2.968826,1.661883,Alc4,OC(CC1=CC=CC=C1)C2=CC=C(C)C=C2,6.855471,-1.237513,-0.676649,-4.379282,-3.742667,11
4,PC1,O=C1C2=C(C=CC=C2)[Si](C)(C)C3=CC=CC=C31,4.030498,-2.743580,-1.277230,-2.912950,0.715598,-2.968826,1.661883,Alc5,OC(CC1=CC=CC=C1)C2=CC=C(OC)C=C2,1.115037,-2.939343,-1.065685,-1.497640,-2.268652,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,18.950461,-4.845609,2.049338,0.287101,-0.076405,2.183570,0.083274,Alc10,OC(CC1=CC=CC=C1)C2=CC=CS2,11.936778,-8.284666,0.948171,2.748463,7.046379,5
192,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,18.950461,-4.845609,2.049338,0.287101,-0.076405,2.183570,0.083274,Alc11,OC(CC1=CC=CC=C1)C2=CC=C3C(C=CC=C3)=C2,3.628756,8.256067,0.226789,1.520825,1.202459,0
193,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,18.950461,-4.845609,2.049338,0.287101,-0.076405,2.183570,0.083274,Alc12,OC(CC1=CC=CC=C1)C2=C3C(C=CC=C3)=CC=C2,3.303675,8.110436,-0.245090,1.383276,1.102638,0
194,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,18.950461,-4.845609,2.049338,0.287101,-0.076405,2.183570,0.083274,Alc13,OC(CC1=CC=CC=C1)C2=CC(OCO3)=C3C=C2,-1.837692,-3.450207,-2.501756,6.828512,-3.177106,36
195,PC14,O=C1C2=C(C=CC=C2)[Si](C3=CC=CC=C3)(C4=CC=CC=C4...,18.950461,-4.845609,2.049338,0.287101,-0.076405,2.183570,0.083274,Alc14,OC(CC1=CC=CC=C1)C2=CC=C3C(OCCO3)=C2,-5.024676,-1.642872,-3.669234,4.564398,-1.730443,61